### ISSUE TITLE
Enable molecule v3 support

### ISSUE THREAD

**Issue by jaredledvina** [ansible-community/molecule-inspec#2]
Hi folks!

Now that this is broken out into a dedicated plugin, is there a correct configuration to enable it w/ molecule v3? 

Per IRC, my understanding that this plugin is no longer supported with v3 and that there's required work from the community to maintain/enable that support. 

If anyone has pointers on what work is required, I'm happy to give adding that support a whirl. An example PR would be great to reference.

**Comment by abtreece** [comment]
Hey @jaredledvina,

This verifier does work with Molecule 3.X. The first step is installing the plugin along with molecule via `pip`...

```
$ pip list | grep molecule
molecule                   3.2.0a0
molecule-docker            0.3.3
molecule-inspec            1.0
```

Once installed you will see `inspec` is available as a verifier...

```
$ molecule init role --help
Usage: molecule init role [OPTIONS] ROLE_NAME

  Initialize a new role for use with Molecule.

Options:
  --dependency-name [galaxy]      Name of dependency to initialize. (galaxy)
  -d, --driver-name [delegated|docker]
                                  Name of driver to initialize. (delegated)
  --lint-name [yamllint]          Name of lint to initialize. (yamllint)
  --provisioner-name [ansible]    Name of provisioner to initialize. (ansible)
  --verifier-name [ansible|inspec|testinfra]
                                  Name of verifier to initialize. (ansible)
  --help                          Show this message and exit.
```

Then initializing the role accordingly...

```
$ molecule init role --driver-name docker --verifier-name inspec test-role
--> Initializing new role test-role...
Initialized role in /.../temp/test-role successfully.
```
